# pokemon service with a Postgres database that exposes the default port 5432

services:
  db:
    image: postgres:latest
    shm_size: 128mb
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: pokemon
    ports:
      - "5432:5432"
    # create the database schema from the schema.sql file
    # this is a relative path to the compose.yaml file
    volumes:
      - ./db/schema.sql:/docker-entrypoint-initdb.d/init.sql
